import { Router } from "express";
import bcrypt from "bcryptjs";
import dns from "dns";
import fs from "fs/promises";
import path from "path";
import http from "http";
import https from "https";
import { db, adminConfigTable } from "@workspace/db";

const router = Router();

const NGINX_CONF_PATH = "/etc/nginx/sites-available/aio-voice-connect.conf";
const NGINX_ENABLED_PATH = "/etc/nginx/sites-enabled/aio-voice-connect.conf";

// On the VPS, process.cwd() === /opt/aio-voice-connect
const INSTALL_DIR = process.cwd();

// Handoff files use /tmp — guaranteed writable by the unprivileged service user.
// The systemd path unit watches for PENDING_CONF; the helper reads/writes these.
const PENDING_CONF = "/tmp/aio-vc-nginx-pending.conf";
const PENDING_DOMAIN = "/tmp/aio-vc-nginx-pending-domain.txt";
const RESULT_FILE = "/tmp/aio-vc-nginx-result.json";

// Stable copy of the nginx config — always written during Validate so the
// manual `sudo cp` command works even if the helper is not yet installed.
const CONFIG_COPY = "/tmp/aio-vc-nginx-config.conf";

// Base (domain-less) config copy — written during domain reset so the
// manual restore command works without any heredoc or file download.
const BASE_CONFIG_COPY = "/tmp/aio-vc-nginx-base.conf";

// ── nginx config builders ────────────────────────────────────────────────────

function nginxLocations(): string {
  return `
    # API → Express on port 3100
    location /api/ {
        proxy_pass         http://127.0.0.1:3100/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    # Frontend → static file server on port 8080
    location / {
        proxy_pass         http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    # Security headers
    add_header X-Frame-Options        "SAMEORIGIN"    always;
    add_header X-Content-Type-Options "nosniff"       always;
    add_header Referrer-Policy        "strict-origin"  always;

    client_max_body_size 16M;`;
}

/**
 * Build an nginx virtual-host config for the given domain.
 *
 * The installer does NOT create any nginx site config — nginx is only
 * configured here, triggered by the user connecting a domain in Settings.
 *
 * Rules:
 * - No `default_server` — that directive belongs to the Debian default site
 *   only; adding it here causes "duplicate default server" when nginx -t runs.
 * - `server_name` is always the explicit domain, never `_`.
 */
function buildNginxConf(domain: string): string {
  return `# aio-voice-connect — generated by domain setup (Settings → Domain)
# Managed by the application; do not edit manually.
#
# nginx is a pure reverse proxy:
#   API (Express):          http://127.0.0.1:3100
#   Frontend (static):      http://127.0.0.1:8080
#
# www → apex redirect
server {
    listen 80;
    listen [::]:80;
    server_name www.${domain};
    return 301 http://${domain}$request_uri;
}

# Domain virtual host
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
${nginxLocations()}
}
`;
}

// ── helpers ──────────────────────────────────────────────────────────────────

async function fileExists(p: string): Promise<boolean> {
  try { await fs.access(p); return true; } catch { return false; }
}

function httpGet(url: string, timeoutMs = 6000): Promise<number> {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith("https") ? https : http;
    const req = lib.get(url, { timeout: timeoutMs }, res => { res.resume(); resolve(res.statusCode ?? 0); });
    req.on("timeout", () => { req.destroy(); reject(new Error("timeout")); });
    req.on("error", reject);
  });
}

/**
 * HTTPS connectivity probe — skips certificate verification.
 * Used to check whether nginx is serving HTTPS correctly.  Cert validity is
 * already guaranteed by certbot; we don't need Node.js to re-verify it here,
 * and doing so causes false negatives when the server's CA bundle lags behind
 * the Let's Encrypt root rotation.
 */
function httpsProbe(domain: string, path: string, timeoutMs = 8000): Promise<number> {
  return new Promise((resolve, reject) => {
    const req = https.get(
      { hostname: domain, path, rejectUnauthorized: false, timeout: timeoutMs },
      res => { res.resume(); resolve(res.statusCode ?? 0); },
    );
    req.on("timeout", () => { req.destroy(); reject(new Error("timeout")); });
    req.on("error", reject);
  });
}

/** Fetch the plain-text body of a URL (used for IP echo services). */
function httpGetText(url: string, timeoutMs = 5000): Promise<string> {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith("https") ? https : http;
    const req = lib.get(url, { timeout: timeoutMs }, res => {
      let body = "";
      res.setEncoding("utf8");
      res.on("data", (chunk: string) => { body += chunk; });
      res.on("end", () => resolve(body.trim()));
    });
    req.on("timeout", () => { req.destroy(); reject(new Error("timeout")); });
    req.on("error", reject);
  });
}

/**
 * Detect the server's own public IPv4 address.
 * Tries three public echo services in order; returns null if all fail.
 * Result is cached in memory for the process lifetime so repeated Validate
 * clicks don't hammer external services.
 */
let _cachedServerIp: string | null | undefined = undefined; // undefined = not fetched yet

async function getServerPublicIp(): Promise<string | null> {
  if (_cachedServerIp !== undefined) return _cachedServerIp;
  const services = [
    "https://api.ipify.org",
    "https://checkip.amazonaws.com",
    "http://ifconfig.me/ip",
  ];
  for (const url of services) {
    try {
      const ip = await httpGetText(url);
      // Basic sanity check — must look like an IPv4 address
      if (/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)) {
        _cachedServerIp = ip;
        return ip;
      }
    } catch { /* try next */ }
  }
  _cachedServerIp = null;
  return null;
}

/** Resolve a domain using Google/Cloudflare to bypass OS DNS cache. */
async function resolveDomain(domain: string): Promise<string[]> {
  const resolver = new dns.promises.Resolver();
  resolver.setServers(["8.8.8.8", "1.1.1.1"]);
  return resolver.resolve4(domain);
}

/**
 * Write trigger files and wait up to 30 s for the systemd path-unit helper
 * to process them and write nginx-setup-result.json.
 * Returns null if the helper never responds (not installed / not running).
 *
 * Always writes CONFIG_COPY (/tmp/aio-vc-nginx-config.conf) so the manual
 * `sudo cp` command works even if the helper times out.
 */
async function runHelper(conf: string, domain: string): Promise<{
  ok: boolean; sslOk?: boolean; sslError?: string; step?: string; error?: string;
} | null> {
  // Always write a stable copy the user can cp from manually
  await fs.writeFile(CONFIG_COPY, conf, "utf8").catch(() => {});

  // Clear any stale result from a previous run
  await fs.unlink(RESULT_FILE).catch(() => {});

  // Write trigger files — systemd path unit watches for PENDING_CONF
  await fs.writeFile(PENDING_CONF, conf, "utf8");
  await fs.writeFile(PENDING_DOMAIN, domain, "utf8");

  const TIMEOUT = 30_000;
  const INTERVAL = 500;
  const deadline = Date.now() + TIMEOUT;

  while (Date.now() < deadline) {
    await new Promise(r => setTimeout(r, INTERVAL));
    try {
      const raw = await fs.readFile(RESULT_FILE, "utf8");
      await fs.unlink(RESULT_FILE).catch(() => {});
      return JSON.parse(raw.trim());
    } catch {
      // Not ready yet — keep polling
    }
  }

  // Timeout — clean up trigger files but keep CONFIG_COPY for manual use
  await fs.unlink(PENDING_CONF).catch(() => {});
  await fs.unlink(PENDING_DOMAIN).catch(() => {});
  return null;
}

function manualSetupCommands(domain: string): string[] {
  return [
    // CONFIG_COPY is written by the API server at validate time — no SCP needed.
    `sudo cp ${CONFIG_COPY} ${NGINX_CONF_PATH}`,
    `sudo ln -sf ${NGINX_CONF_PATH} ${NGINX_ENABLED_PATH}`,
    `sudo nginx -t && sudo systemctl reload nginx`,
    certbotCmd(domain),
  ];
}

function certbotCmd(domain: string): string {
  // --no-eff-email suppresses the "share email with EFF?" interactive prompt
  // that certbot shows even with --non-interactive on first run.
  return `sudo certbot --nginx -d ${domain} --non-interactive --agree-tos --no-eff-email --email admin@${domain}`;
}

/** Manual commands to enable SSL. */
function sslManualCommands(domain: string): string[] {
  return [certbotCmd(domain)];
}

/**
 * Manual commands to remove the nginx domain config after domain reset.
 * The symlink must be removed first so nginx -t / reload succeeds with
 * only the Debian default site remaining.
 */
function cleanupCommands(): string[] {
  return [
    `sudo rm -f ${NGINX_ENABLED_PATH}`,
    `sudo rm -f ${NGINX_CONF_PATH}`,
    `sudo systemctl reload nginx`,
  ];
}

// ── routes ───────────────────────────────────────────────────────────────────

// GET /api/setup/status
router.get("/setup/status", async (_req, res) => {
  try {
    const config = await db.query.adminConfigTable.findFirst();
    res.json({ setupComplete: config?.setupComplete ?? false });
  } catch {
    res.json({ setupComplete: false });
  }
});

// POST /api/setup — create admin account
router.post("/setup", async (req, res) => {
  const { username, password, language, timezone } = req.body as {
    username: string; password: string; language: "en" | "fr"; timezone: string;
  };
  if (!username || !password || !language || !timezone) {
    res.status(400).json({ error: "All fields are required" }); return;
  }
  if (username.length < 3) { res.status(400).json({ error: "Username must be at least 3 characters" }); return; }
  if (password.length < 8) { res.status(400).json({ error: "Password must be at least 8 characters" }); return; }

  const existing = await db.query.adminConfigTable.findFirst();
  if (existing?.setupComplete) { res.status(409).json({ error: "Setup already complete" }); return; }

  const passwordHash = await bcrypt.hash(password, 12);
  const now = new Date();
  if (existing) {
    await db.update(adminConfigTable).set({ username, passwordHash, language, timezone, setupComplete: true, updatedAt: now });
  } else {
    await db.insert(adminConfigTable).values({ username, passwordHash, language, timezone, setupComplete: true });
  }
  const config = await db.query.adminConfigTable.findFirst();
  req.session.adminId = config!.id;
  req.session.username = config!.username;
  res.json({ ok: true });
});

// GET /api/setup/domain/nginx-config — download the generated nginx config
router.get("/setup/domain/nginx-config", (req, res) => {
  const domain = typeof req.query.domain === "string" ? req.query.domain.trim() : null;
  if (!domain) { res.status(400).send("domain query parameter is required"); return; }
  if (!/^[a-zA-Z0-9][a-zA-Z0-9.-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$/.test(domain)) {
    res.status(400).send("Invalid domain"); return;
  }
  const conf = buildNginxConf(domain);
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="aio-voice-connect.conf"`);
  res.send(conf);
});

// DELETE /api/setup/domain — reset domain in DB and remove the nginx site config.
//
// Strategy: signal the privileged helper with an empty config (empty file =
// delete mode in nginx-helper.sh). The helper removes the conf + symlink and
// reloads nginx so the Debian default site takes over on port 80.
// Falls back to manual `rm` commands if the helper is not available.
router.delete("/setup/domain", async (_req, res) => {
  // Always reset DB first regardless of nginx outcome
  await db.update(adminConfigTable).set({ domain: null, domainConfigured: false, updatedAt: new Date() }).catch(() => {});

  // Empty PENDING_CONF triggers delete mode in nginx-helper.sh
  const helperResult = await runHelper("", "");

  if (helperResult !== null && helperResult.ok) {
    res.json({ ok: true, message: "Domain removed — nginx site configuration deleted." });
    return;
  }

  // Helper not available or failed — return manual removal commands
  res.json({
    ok: false,
    needsManual: true,
    message: "Run these commands to remove the nginx domain configuration:",
    cleanupCommands: cleanupCommands(),
  });
});

// POST /api/setup/domain — configure nginx + SSL
//
// The app runs under systemd with CapabilityBoundingSet=CAP_NET_BIND_SERVICE,
// which means sudo and setuid are blocked in the service process.
//
// One-click flow: write trigger files → poll for the privileged
// nginx-helper.sh result (run as root via aio-nginx-setup.path systemd unit).
//
// Graceful fallback: if the helper is not installed or doesn't respond within
// 30 s, check whether files are already in place (manual setup), then do an
// HTTP probe. If everything looks good, save and report success; otherwise
// return manual setup instructions.
router.post("/setup/domain", async (req, res) => {
  const { domain } = req.body as { domain: string };
  if (!domain || !/^[a-zA-Z0-9][a-zA-Z0-9.-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$/.test(domain)) {
    res.status(400).json({ error: "Invalid domain name" }); return;
  }

  const steps: { step: string; success: boolean; error?: string }[] = [];

  // ── Step 0: Resolve domain + verify it points to this server ─────────────
  // Both checks run in parallel to save time.
  let resolvedIps: string[] = [];
  let serverIp: string | null = null;

  try {
    [resolvedIps, serverIp] = await Promise.all([
      resolveDomain(domain),
      getServerPublicIp(),
    ]);
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    steps.push({
      step: "DNS A record check",
      success: false,
      error: code === "ENOTFOUND"
        ? `${domain} does not resolve — point an A record to this server's IP and wait for propagation (5–15 min, up to 48h). Run \`dig @8.8.8.8 ${domain} A\` to verify.`
        : `DNS lookup failed: ${code ?? String(err)}`,
    });
    res.json({ ok: false, error: "DNS not configured yet", steps });
    return;
  }

  // Check that at least one resolved IP matches this server's public IP
  if (serverIp && !resolvedIps.includes(serverIp)) {
    steps.push({
      step: `DNS A record check — ${domain} → ${resolvedIps.join(", ")}`,
      success: false,
      error: `Domain points to ${resolvedIps.join(", ")} but this server's public IP is ${serverIp}. Update your DNS A record to point to ${serverIp} and wait for propagation (5–15 min, up to 48h).`,
    });
    res.json({ ok: false, error: "Domain does not point to this server", steps });
    return;
  }

  // DNS resolves and points to this server
  steps.push({
    step: `DNS resolved via 8.8.8.8 → ${resolvedIps.join(", ")}${serverIp ? ` ✓ matches server IP` : ""}`,
    success: true,
  });

  // ── Step 1: try the privileged helper (systemd path unit) ────────────────
  const conf = buildNginxConf(domain);
  const helperResult = await runHelper(conf, domain);

  if (helperResult !== null) {
    // Helper responded — build step list from its result
    if (!helperResult.ok) {
      steps.push({
        step: helperResult.step ?? "nginx setup",
        success: false,
        error: helperResult.error ?? "Unknown error",
      });
      res.json({ ok: false, needsManual: false, domain, steps, cleanupCommands: cleanupCommands() });
      return;
    }

    steps.push({ step: "nginx config written & site enabled", success: true });
    steps.push({ step: "nginx reloaded", success: true });

    if (helperResult.sslOk) {
      steps.push({ step: "SSL certificate issued (Let's Encrypt)", success: true });
    } else {
      steps.push({
        step: "SSL certificate",
        success: false,
        error: helperResult.sslError ?? "certbot did not complete — see /var/log/letsencrypt/",
      });
    }

    await db.update(adminConfigTable).set({ domain, domainConfigured: true, updatedAt: new Date() });

    res.json({
      ok: true, domain, sslOk: helperResult.sslOk, steps,
      ...(helperResult.sslOk ? {} : {
        manualCommands: sslManualCommands(domain),
      }),
    });
    return;
  }

  // ── Helper not responding — check if files are already in place ───────────
  steps.push({
    step: "Auto-setup helper",
    success: false,
    error: "Helper service not responding (run update.sh to install it), checking for manual setup…",
  });

  const [confExists, linkExists] = await Promise.all([
    fileExists(NGINX_CONF_PATH),
    fileExists(NGINX_ENABLED_PATH),
  ]);

  if (!confExists) {
    steps.push({ step: "Nginx config file", success: false, error: "File not found" });
    res.json({ ok: false, needsManual: true, domain, steps, manualCommands: manualSetupCommands(domain), cleanupCommands: cleanupCommands() });
    return;
  }
  steps.push({ step: "Nginx config file exists", success: true });

  if (!linkExists) {
    steps.push({ step: "Site enabled symlink", success: false, error: `${NGINX_ENABLED_PATH} not found` });
    res.json({
      ok: false, needsManual: true, domain, steps,
      manualCommands: [
        `sudo ln -sf ${NGINX_CONF_PATH} ${NGINX_ENABLED_PATH}`,
        `sudo nginx -t && sudo systemctl reload nginx`,
        ...sslManualCommands(domain),
      ],
      cleanupCommands: cleanupCommands(),
    });
    return;
  }
  steps.push({ step: "Site enabled (symlink exists)", success: true });

  // HTTP probe — verify nginx is actually serving the domain
  let httpOk = false;
  try {
    const status = await httpGet(`http://${domain}/api/healthz`);
    httpOk = status >= 200 && status < 500;
    steps.push({ step: `HTTP probe → ${status}`, success: httpOk, error: httpOk ? undefined : `Unexpected status ${status}` });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    steps.push({ step: "HTTP probe", success: false, error: `Cannot reach http://${domain}: ${msg}` });
    res.json({
      ok: false, needsManual: true, domain, steps,
      manualCommands: [
        `sudo nginx -t`,
        `sudo systemctl reload nginx`,
        ...sslManualCommands(domain),
      ],
      cleanupCommands: cleanupCommands(),
    });
    return;
  }

  // SSL probe — skips cert verification (certbot guarantees cert validity;
  // Node's CA bundle may lag Let's Encrypt roots causing false negatives)
  let sslOk = false;
  try {
    const status = await httpsProbe(domain, "/api/healthz");
    sslOk = status >= 200 && status < 500;
    steps.push({ step: `HTTPS probe → ${status}`, success: sslOk });
  } catch {
    steps.push({ step: "HTTPS / SSL", success: false, error: "Port 443 not reachable — check firewall rules" });
  }

  await db.update(adminConfigTable).set({ domain, domainConfigured: true, updatedAt: new Date() });
  res.json({
    ok: true, domain, sslOk, steps,
    ...(sslOk ? {} : {
      manualCommands: sslManualCommands(domain),
    }),
  });
});

export default router;
